# NUMPY

# CREATING ARRAY

In [1]:
import numpy as np
arr_1d = np.array([1,2,3,4,5,6,7,8,9])
print(arr_1d)

[1 2 3 4 5 6 7 8 9]


In [6]:
import numpy as np
arr_2d =np.array([[1,2,3,4],[5,6,7,8]])
print(arr_2d)

[[1 2 3 4]
 [5 6 7 8]]


In [8]:
import numpy as np
arr_3d= np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])
print(arr_3d)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]


# ARRAY GENERATION FUNCTION

In [11]:
import numpy as np
arr = np.arange(1,11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [12]:
import numpy as np
# (start,end,step)
arr_step = np.arange(1,11,2)
print(arr_step)

[1 3 5 7 9]


In [14]:
import numpy as np
zero = np.zeros(6)
print(zero)

[0. 0. 0. 0. 0. 0.]


In [16]:
import numpy as np
# ((rows,coloumns)
arr_zero = np.zeros((4,3))
print(arr_zero)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [17]:
import numpy as np
arr = np.ones(6)
print(arr)

[1. 1. 1. 1. 1. 1.]


In [18]:
import numpy as np
arr_one = np.ones((3,5))
print(arr_one)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [19]:
# linerspace  -->linspace()
import numpy as np
arr = np.linspace(1,5,2)
print(arr)

[1. 5.]


In [20]:
import numpy as np
arr = np.linspace(1,10,3)
print(arr)

[ 1.   5.5 10. ]


In [21]:
import numpy as np
arr = np.linspace(1,50,100)
print(arr)

[ 1.          1.49494949  1.98989899  2.48484848  2.97979798  3.47474747
  3.96969697  4.46464646  4.95959596  5.45454545  5.94949495  6.44444444
  6.93939394  7.43434343  7.92929293  8.42424242  8.91919192  9.41414141
  9.90909091 10.4040404  10.8989899  11.39393939 11.88888889 12.38383838
 12.87878788 13.37373737 13.86868687 14.36363636 14.85858586 15.35353535
 15.84848485 16.34343434 16.83838384 17.33333333 17.82828283 18.32323232
 18.81818182 19.31313131 19.80808081 20.3030303  20.7979798  21.29292929
 21.78787879 22.28282828 22.77777778 23.27272727 23.76767677 24.26262626
 24.75757576 25.25252525 25.74747475 26.24242424 26.73737374 27.23232323
 27.72727273 28.22222222 28.71717172 29.21212121 29.70707071 30.2020202
 30.6969697  31.19191919 31.68686869 32.18181818 32.67676768 33.17171717
 33.66666667 34.16161616 34.65656566 35.15151515 35.64646465 36.14141414
 36.63636364 37.13131313 37.62626263 38.12121212 38.61616162 39.11111111
 39.60606061 40.1010101  40.5959596  41.09090909 41.

# RANDOM GENERSTION FUNCTION

In [22]:
np.random.rand(10)

array([0.22535155, 0.36193735, 0.20858667, 0.28819823, 0.92345438,
       0.7243319 , 0.99752051, 0.12991586, 0.68788316, 0.1073656 ])

In [24]:
np.random.rand(20)

array([0.98943968, 0.8165657 , 0.20488374, 0.9443244 , 0.38356456,
       0.5821773 , 0.47843551, 0.45720133, 0.21750123, 0.60581038,
       0.67105438, 0.53469336, 0.81810705, 0.39102412, 0.26610763,
       0.61003164, 0.87317105, 0.95234764, 0.21710835, 0.8980115 ])

In [25]:
# it generate 0-6 a random number generate 
np.random.randint(6)

3

In [28]:
np.random.randint(10,20,10)

array([10, 13, 13, 16, 17, 11, 17, 12, 14, 10], dtype=int32)

In [29]:
np.random.rand(1,4,10)

array([[[0.67399873, 0.87780728, 0.76699264, 0.96464438, 0.50671848,
         0.84626837, 0.74517107, 0.9284772 , 0.1969687 , 0.70344126],
        [0.98722438, 0.2335295 , 0.10860685, 0.21047548, 0.62565292,
         0.00484755, 0.8054697 , 0.92870047, 0.64761643, 0.38370635],
        [0.96643507, 0.63839286, 0.00893228, 0.64595362, 0.76336503,
         0.0731783 , 0.09112373, 0.58904063, 0.26765537, 0.74152614],
        [0.44990112, 0.95994002, 0.5637028 , 0.46385288, 0.66801634,
         0.56342268, 0.56211102, 0.0612248 , 0.51396593, 0.42251332]]])

# ARRRAY ATTRIBUTES

In [31]:
import numpy as np
arr = np.array([[1,3,4,5],[1,2,7,6],[3,5,8,9]])
print(arr)
arr.shape

[[1 3 4 5]
 [1 2 7 6]
 [3 5 8 9]]


(3, 4)

In [32]:
arr.size

12

In [33]:
arr.dtype

dtype('int64')

# ARRAY METHODES

In [40]:
import numpy as np
arr= np.array([[22,13,24,5],[3,45,44,6]])
print(arr)

[[22 13 24  5]
 [ 3 45 44  6]]


In [41]:
arr.min()

np.int64(3)

In [42]:
arr.max()

np.int64(45)

In [43]:
arr.sum()

np.int64(162)

In [44]:
arr.mean()

np.float64(20.25)

In [45]:
# in case coloumns sum
np.sum(arr,axis = 0)

array([25, 58, 68, 11])

In [46]:
# in case row sum
np.sum(arr,axis = 1)

array([64, 98])

In [47]:
arr.std()

np.float64(15.730146216739373)

In [48]:
# maximum element index number
arr.argmax()

np.int64(5)

In [49]:
# minimum element index number 
arr.argmin()

np.int64(4)

# RESHAPING AND RESIZING

In [4]:
import numpy as np
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [5]:
arr.reshape(6,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

# NUMPY INDEXING AND SLICING OF VECTROS

In [9]:
import numpy as np
arr1 = np.arange(11,21)
arr1

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [11]:
arr1[6]

np.int64(17)

In [13]:
arr1[9]

np.int64(20)

In [14]:
# sicing
arr1[1:5]

array([12, 13, 14, 15])

In [15]:
arr1[:6]

array([11, 12, 13, 14, 15, 16])

In [16]:
arr1[4: ]

array([15, 16, 17, 18, 19, 20])

In [17]:
# [start,end,step]
arr1[2:8:2]

array([13, 15, 17])

# NUMPY INDEXING AND SCLICING OF MATRIX

In [19]:
import numpy as np
arr =np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [20]:
# it targate rows
arr[0]

array([1, 2, 3, 4, 5])

In [21]:
arr[1]

array([ 6,  7,  8,  9, 10])

In [22]:
arr[5]

array([26, 27, 28, 29, 30])

In [23]:
arr[0,0]

np.int64(1)

In [24]:
arr[0,4]

np.int64(5)

In [25]:
arr[5,4]

np.int64(30)

In [26]:
arr[3,2]

np.int64(18)

In [27]:
# slicing
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [28]:
slice = arr[3:,3:]
slice

array([[19, 20],
       [24, 25],
       [29, 30]])

In [31]:
slice1= arr[2:4,2:4]
slice1

array([[13, 14],
       [18, 19]])

# BOOLEAN INDEXING

In [2]:
import numpy as np
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [3]:
bool_index = arr%2 ==0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [4]:
arr = arr[bool_index]
arr

array([12, 14, 16, 18, 20])

# ARRAY OPERATION

In [6]:
import numpy as np
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])
print(a1)
print(a2)

[1 2 3 4 5]
[ 6  7  8  9 10]


In [7]:
a1+a2

array([ 7,  9, 11, 13, 15])

In [8]:
sub = a1-a2
print(sub)

[-5 -5 -5 -5 -5]


In [9]:
a1*a2

array([ 6, 14, 24, 36, 50])

In [10]:
a1/a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [11]:
a1//a2

array([0, 0, 0, 0, 0])

In [12]:
a1**a2

array([      1,     128,    6561,  262144, 9765625])

In [15]:
# BROADCASTING
import numpy as np
l = np.array([1,4,6,5,3])
l+10

array([11, 14, 16, 15, 13])

In [21]:
import numpy as np
arr2 = np.arange(1,26).reshape(5,5)
print(arr2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [22]:
arr2 *2

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40],
       [42, 44, 46, 48, 50]])

In [32]:
# DEEP AND SHALLOW COPY
import numpy as np
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [33]:
slice  = a[:5]
slice

array([1, 2, 3, 4, 5])

In [27]:
slice = slice *10
slice

array([100, 200, 300, 400, 500])

In [28]:
a[4:6] *10

array([50, 60])

In [29]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

# 

b= a
b[0] = 99
b

In [31]:
a

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

# MATRIX OPERATION

In [41]:
import numpy as np
mat1 = np.array([[1,2,3],[4,5,6]])
mat2 = np.array([[[7,8,9],[1,2,3],[4,6,8]]])
print(mat1)

[[1 2 3]
 [4 5 6]]


In [42]:
mat2

array([[[7, 8, 9],
        [1, 2, 3],
        [4, 6, 8]]])

In [43]:
mat1 @ mat2

array([[[21, 30, 39],
        [57, 78, 99]]])

In [44]:
np.dot(mat1,mat2)

array([[[21, 30, 39]],

       [[57, 78, 99]]])

In [50]:
# Transpose of matrix
# [2,4,-1]              [2,-10,18]
# [-10,5,11]    -->     [4,5,-7]
# [18,-7,6]             [-1,11,6]

import numpy as np
a = np.array([[2,4,-1],[-10,5,11],[-1,11,6]])
a

array([[  2,   4,  -1],
       [-10,   5,  11],
       [ -1,  11,   6]])

In [51]:
transpose = a.T
print(transpose)

[[  2 -10  -1]
 [  4   5  11]
 [ -1  11   6]]


# ADVANCE ARRAY MANIPULATION

In [54]:
# vertical
import numpy as np
mat1 = np.array([1,2,3,4,5,6])
mat2 = np.array([3,4,5,2,6,7])
np.vstack((mat1,mat2))

array([[1, 2, 3, 4, 5, 6],
       [3, 4, 5, 2, 6, 7]])

In [55]:
# horizontal
np.hstack((mat1,mat2))

array([1, 2, 3, 4, 5, 6, 3, 4, 5, 2, 6, 7])

In [57]:
np.column_stack((mat1,mat2))

array([[1, 3],
       [2, 4],
       [3, 5],
       [4, 2],
       [5, 6],
       [6, 7]])

# SPLITTING ARRAY

In [58]:
import numpy as np
arr = np.arange(16).reshape(4,4)
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [59]:
np.hsplit(arr,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [60]:
np.hsplit(arr,4)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [61]:
np.vsplit(arr,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [62]:
np.vsplit(arr,4)

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

# NUMPY EXERSISE

In [68]:
import numpy as np
s = np.array([[5,3,4,6,7,8,9,1,2],          #sum =  45
             [6,7,2,1,9,5,3,4,8],           #sum =  45
             [1,9,8,3,4,2,5,6,7],           #sum =  45
                                                               #in case of rows and coloums line sum is 45
             [8,5,9,7,6,1,4,2,3],           #sum =  45
             [4,2,6,8,5,3,7,9,1],           #sum =  45
             [7,1,3,9,2,4,8,5,6],           #sum =  45

             [9,6,1,5,3,7,2,8,4],           #sum =  45
             [2,8,7,4,1,9,6,3,5],           #sum =  45
             [3,4,5,2,8,6,1,7,9]            #sum =  45
])

In [77]:
s.sum()

np.int64(405)

In [82]:
b = np.sum(s,axis = 1)
for i in b:
    if i != 45:
        print("sudo is not valid")
        break
else:
    print("for rows is valid")

for rows is valid


In [66]:
np.sum(s,axis = 0)

array([45, 45, 45, 45, 45, 45, 45, 45, 45])

In [83]:
s[0:3,0:3]

array([[5, 3, 4],
       [6, 7, 2],
       [1, 9, 8]])

In [85]:
for i in range(0,9,3):
    for j in range(0,9,3):
        n= s[i:i+3,j:j+3]
        print(n.sum())

45
45
45
45
45
45
45
45
45


# 2.GENERAL QUESTIONS

In [22]:
import numpy as np
# coloumns: [AGE,MATH MARK, SCIENCE MARKS]
data = np.array([[18,85,78],
                 [19,92,88],
                 [17,76,95],
                 [18,65,78],
                 [20,90,85]
])

In [23]:
# shape of the matrix
data.shape

(5, 3)

In [24]:
# finde the avarage age of the matrix 
np.mean(data[:,0])

np.float64(18.4)

In [25]:
# extract maths of all mark
data[:,1]

array([85, 92, 76, 65, 90])

In [26]:
# find heighest science mark
np.max(data[:,2])

np.int64(95)

In [27]:
# het details of the student who score more than 90 in math
data[:,1]>90

array([False,  True, False, False, False])

In [32]:
# increase math marks of all student by 5
data[:,1] =+5
data

array([[18,  5, 78],
       [19,  5, 88],
       [17,  5, 95],
       [18,  5, 78],
       [20,  5, 85]])

In [37]:
# find how many student are younger than 19
len(data[data[:,0]<19])

3

In [38]:
# calculate the avarage markes in each subject (coloum-wise mean)
np.mean(data[:,1:], axis = 0)

array([ 5. , 84.8])

In [40]:
data

array([[18,  5, 78],
       [19,  5, 88],
       [17,  5, 95],
       [18,  5, 78],
       [20,  5, 85]])

In [44]:
# replace all science mark<85 with 0
data[:,2][data[:,2]<85]=0
data

array([[18,  5,  0],
       [19,  5, 88],
       [17,  5, 95],
       [18,  5,  0],
       [20,  5, 85]])